language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - dev
  - "/^feature.*$/"
  - "/^release.*$/"
script: npm test
before_deploy: npm install now --no-save
deploy:
- provider: script
  script: now --local-config=now-stage.json --team ibcol --token $NOW_TOKEN
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^feature.*|^release.*"
- provider: script
  script: now --local-config=now-stage.json --team ibcol --token $NOW_TOKEN && now
    alias --local-config=now-stage.json --team ibcol --token $NOW_TOKEN
  skip_cleanup: true
  on:
    repo: ibcol/ibcol
    branch: dev
- provider: script
  script: now --local-config=now-production.json --team ibcol --token $NOW_TOKEN &&
    now alias --local-config=now-production.json --team ibcol --token $NOW_TOKEN
  skip_cleanup: true
  on:
    repo: ibcol/ibcol
    branch: master
env:
  global:
  - secure: kzh4kj/eMyrmXdvfpwzyurZ5rVYqlz4TKfp16ZNF6ylCysE+iB9DJkJKBLHGpby8Ool0vEsZPH57Ks676ErmobqeyfRGRNFa5aIo7JM48ZnCofxSMOsIaoBzET90OhC7+SoaveRcubQpXX+6kHgLYGoDhiJtKcV6+481TnvtUcHMu47A0eo1OI9xG8mkAzNsZQtMPHKXyh2eevKI6sCKvaXYp8XAY/50kRlyLXqS7CXTkPkumfRI7XVXb/0/q3rOPnQuSiyLfqUQ0SJDx4Lrp3lBTSII5ovb3B1IasU/u5RnyUK+UQbnWlF2MItr3sNc4vGEXnGWifzfzUbWBo0CziQNijP4J8U6XFZGjywjDY2IaA5F9B9Ft/CrrUGB4iOY+AJY6Ayd5V2W39M0o7uQ2tmw4qnphcWFJIiNz4SnfxxJ8dEsSSXKS8QtIkZ3iaF0dHHc/NjNWC3vkNfLOeer/1ebt04UGMLVMH+DA3RiyFCNnAZ+zcHJf8jLIMcSq04tijAwoLiANo6jROh24/1AqN24/4e9TQ1Dde0JIwgdaDyU/vv9GOI/UwFt6WVlWWdi1DLCboRPwx0LohH/h55kCtsjtlvTpongAfAbTr2pJ1lLxw9oJ2dz8kVE8q4/uDHlICDlzkVq+ew11AQROtcA9Rb+Z88PgKAHKA55r+a5utA=
  - secure: BsbGz/0R5EVYWVYjcDRx6MHg7daK4JPgvfzMOfF9RfuRvWxw3bNduA74T6nPwIuVyCNh5TdXHtjNbd8A9S6+1LvM+rDIrh7h447uGts4kUW2MOsAEMpfvSxk/2K2gHctPy4KejBTwKEiQCYmHc6RVGGlPbaLLU/TIZifFPL5GcNUI0jv0+1N1p8FyI2xZgUi226vwQkuloYQN0oH0XKHu9jof1gsoxpf/rMQoY473PBqlrfIDruAX1noNcUfy0OI/GxESjRToxmdI8R6i3accJPFQz2CRUwQfa/QvHNH7puMvPqGlxIL0mesWBnPRNxa+fe1IYATiMV3NQe2pL8B7jOCdJs1BXaJkPkN81Dj9168+wBKn8TmBwIWGmf+/vGI0r7IR6MWoIJuY5JyRI59M2fEIfwxXz7PV/AzNac0TcsMnutevPjrCcj5Kl3SWGzybUMv5ZjRkMfGRAkWRMwKcY3bn5L8xJGugMHxMiy5asTbp0csWBAXiCjY6ogwPG4vERPA7coBcGdoj2jnSK7ViHzObYXrd1WBWCK/fYYst5g5f8CGRY7GLDo1sgXSh9PCBMv4F2aNYTwsZ3yn+Xssgvlm8wfvrbKGV8vqRfsj8ejPxiw89Y/G9eCy+9st1g4gZ2qT1Vm5zA75ntCKYQFAddbJsUTo0krZbasGWjX1pzE=
notifications:
  slack:
    rooms:
      - ibcol:$SLACK_KEY#web-dev