language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - dev
  - "/^feature.*$/"
  - "/^release.*$/"
env:
  global:
    secure: Ucg0ETYCwYFA8PkrEqs9sHwvdYduVC950QUnaLDzgLxbCbkyUj3CtthpLGdoeQOjLL+IYVWDnIrtRF0uO6tpQUrJ436j0f3bh2v7fhHloTMwindKHBX30gRdqCGyocNq87lrkEGMNs1x+2xJto/md/Z+4kipMcVzyF6pIlBwpDtWwEQQw1XiwcwUgt3jCno3Sa5F7U3OBUkrjhYGZ8wf6xw2eKIkgWIPDsDwQ/T/mMS68/Jbh6HWPbui2PoLZ5L8Py05djaR4H8Al9Euv19A1r8Z4wPtKTtwNYcbKnF+ns/aTA21lIjfutZ5lj14HCI1B4+lcLKubIsyLTfpZ1Rd2+flPxiwQhFABOdPjebWNrbAEcGcX/Y0HWl5FPM+MRY5cuV967KT6y6929cqjZpqRddw/dRq7ZjXmUmJZhTunSbxfECWqvGoeN9AeLy3anXtcgWa5KP4UumIaL63fy+K/QNRaMHjxsOGXmpMJlKUc/FWYPvXPBPBzmXdOdzy4JSTpsz6SV4Cb+2bKe779bHJm36huI5Po/QmDpZeOQvk3Cpifc4nwwy2FziEVOYfwvGmQiGUN41VYjhJkSWcsV5n/gQ6Uqq2aZQcupn0K89Y58oArGE1dMxXhccpmn7U4brVBHWDXj17PsW31cm9VgFHcU2B2BZqPYFEl0BCrVUCYdM=
script: npm test
before_deploy: npm install now --no-save
deploy:
- provider: script
  script: echo "HELLO" && echo $NOW_TOKEN
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^feature.*|^release.*"
- provider: script
  script: now --local-config=now-stage.json --team ibcol --token $NOW_TOKEN && now
    alias --local-config=now-stage.json --team ibcol --token $NOW_TOKEN
  skip_cleanup: true
  on:
    repo: ibcol/ibcol
    branch: dev
- provider: script
  script: now --local-config=now-production.json --team ibcol --token $NOW_TOKEN &&
    now alias --local-config=now-production.json --team ibcol --token $NOW_TOKEN
  skip_cleanup: true
  on:
    repo: ibcol/ibcol
    branch: master
