language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - dev
  - "/^feature.*$/"
  - "/^release.*$/"
script: npm test
before_deploy: npm install now --no-save
deploy:
- provider: script
  script: now --local-config=now-stage.json --team ibcol --token $NOW_TOKEN
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^feature.*|^release.*"
- provider: script
  script: now --local-config=now-stage.json --team ibcol --token $NOW_TOKEN && now
    alias --local-config=now-stage.json --team ibcol --token $NOW_TOKEN
  skip_cleanup: true
  on:
    repo: ibcol/ibcol
    branch: dev
- provider: script
  script: now --local-config=now-production.json --team ibcol --token $NOW_TOKEN &&
    now alias --local-config=now-production.json --team ibcol --token $NOW_TOKEN
  skip_cleanup: true
  on:
    repo: ibcol/ibcol
    branch: master
env:
  global:
    secure: kzh4kj/eMyrmXdvfpwzyurZ5rVYqlz4TKfp16ZNF6ylCysE+iB9DJkJKBLHGpby8Ool0vEsZPH57Ks676ErmobqeyfRGRNFa5aIo7JM48ZnCofxSMOsIaoBzET90OhC7+SoaveRcubQpXX+6kHgLYGoDhiJtKcV6+481TnvtUcHMu47A0eo1OI9xG8mkAzNsZQtMPHKXyh2eevKI6sCKvaXYp8XAY/50kRlyLXqS7CXTkPkumfRI7XVXb/0/q3rOPnQuSiyLfqUQ0SJDx4Lrp3lBTSII5ovb3B1IasU/u5RnyUK+UQbnWlF2MItr3sNc4vGEXnGWifzfzUbWBo0CziQNijP4J8U6XFZGjywjDY2IaA5F9B9Ft/CrrUGB4iOY+AJY6Ayd5V2W39M0o7uQ2tmw4qnphcWFJIiNz4SnfxxJ8dEsSSXKS8QtIkZ3iaF0dHHc/NjNWC3vkNfLOeer/1ebt04UGMLVMH+DA3RiyFCNnAZ+zcHJf8jLIMcSq04tijAwoLiANo6jROh24/1AqN24/4e9TQ1Dde0JIwgdaDyU/vv9GOI/UwFt6WVlWWdi1DLCboRPwx0LohH/h55kCtsjtlvTpongAfAbTr2pJ1lLxw9oJ2dz8kVE8q4/uDHlICDlzkVq+ew11AQROtcA9Rb+Z88PgKAHKA55r+a5utA=
notifications:
  slack:
    secure: UYQifSQx86Gb+oFRx8WjmgyNsnDoTWPuV+cLqzxn4FvdMaRPQM1AheUDeml+WA95xGda09mFokrBzSpLSPppx9KjaOrxL+QA8StKlqp92eWRXNRwUQQeBLSnthVsyo5E/5QB7qa7PkB6/UU1IAhyLaHkXsr0qGvursP41kxpLWqf2M+7CWw07XcvRofwdgTUA6QdVoKFIgMpw02V7rmEivSyFQLNkf6S/GCZryYLKdsxZLOHAkDheceOKy43pad8BqnhcszPTJjyjRgLSh53lztrILp6vXXxcC64YKjnvMD1IP2aw47q2xoUNowgNRsRihAAPcbdR0qx3WGHYHbLjC+CC4OVo5BUeB7UI7KsKuXaBHLjLRwgKyvtQ6lyBb8TGj988m3jLM6I2n0JH3+px5DlS3pH0PMd7izJqgu8aJoKEzalX6gwXaAZqtr8QQ7SQoy32D4iQ1v+DHiz08CRt8BDLN5Ig7AxhBLh6uqEKfcz0nmDOxUk8E1dWPJ86cOSohNo8NyvHMlGvRNil2wIKdLLyEawGWFSZ0nSKxP18Nnpvwo9T2yQWwJ+BEtDNjbXIuXZf/JMDo36DEBhCmnIgOCbKOkzdO8a5A53A2dPnhfEYAxkeywTU6K00DnkBeYyO6lqmE87FU1SqeKEYR+IzEM35lqYN7Uxa0gJk9gbdP8=
